Repository sebiny/6-moving-team2-BE, pull requests merged in 2025-07, with the labels that each got.

#2 [setting] 초기 프로젝트 셋팅
  .github /pull_request_template.md
  .gitignore
  .prettierrc
  README.md
  openapi.yaml
  package-lock.json
  package.json
  prisma/migrations/20250703071021_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.ts
  src/config/passport.ts
  src/config/prisma.ts
  src/controllers/.gitkeep
  src/dtos/.gitkeep
  src/middlewares/.gitkeep
  src/middlewares/passport/.gitkeep
  src/repositories/.gitkeep
  src/routes/.gitkeep
  src/server.ts
  src/services/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  tsconfig.json
Labels: Chore

#3 [Chore] pr template 생성
  .github /pull_request_template.md
Labels: Chore

#9 [Fix] auth API 디자인에 맞게 수정
  prisma/migrations/20250708081004_update_schema2/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.ts
  src/controllers/AuthController.ts
  src/middlewares/passport/JwtStrategy.ts
  src/repositories/AuthRepository.ts
  src/repositories/ProfileRepository.ts
  src/services/AuthService.ts
  src/services/ProfileService.ts
Labels: Fix

#10 [fix 이지수]토큰페이로드에 유저 타입 추가 및 프로파일 셋팅
  src/controllers/ProfileController.ts
  src/middlewares/passport/JwtStrategy.ts
  src/routes/ProfileRouter.ts
  src/services/AuthService.ts
Labels: Fix

#11 [feat 이지수] profile API 미완성
  prisma/migrations/20250710065525_update_schema/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.ts
  src/controllers/ProfileController.ts
  src/repositories/AuthRepository.ts
  src/repositories/ProfileRepository.ts
  src/routes/ProfileRouter.ts
  src/server.ts
  src/services/ProfileService.ts
Labels: Feature

#14 fix:스키마 수정 및 profile API 수정
  prisma/migrations/20250714053142_update_schema/migration.sql
  prisma/schema.prisma
  src/app.ts
  src/controllers/authController.ts
  src/controllers/profileController.ts
  src/middlewares/passport/JwtStrategy.ts
  src/middlewares/passport/SocialStrategy.ts
  src/repositories/authRepository.ts
  src/repositories/profileRepository.ts
  src/routes/AuthRouter.ts
  src/routes/ProfileRouter.ts
  src/routes/ReviewRouter.ts
  src/routes/authRouter.ts
  src/routes/profileRouter.ts
  src/services/ProfileService.ts
  src/services/ReviewService.ts
  src/services/authService.ts
  src/services/profileService.ts
  src/types/social.d.ts
  src/types/userType.ts
  src/utils/asyncHandler.ts
  src/utils/customError.ts
Labels: Fix

#16 fix:파일이름 수정 및 profile 생성에 UserType 검사 추가
  src/app.ts
  src/config/passport.ts
  src/controllers/auth.controller.ts
  src/controllers/profile.controller.ts
  src/middlewares/passport/jwtStrategy.ts
  src/middlewares/passport/socialStrategy.ts
  src/repositories/auth.Repository.ts
  src/repositories/profile.Repository.ts
  src/routes/auth.router.ts
  src/routes/profile.router.ts
  src/services/auth.service.ts
  src/services/profile.service.ts
Labels: Fix

#20 [Feat] review 생성, 조회 API
  src/app.ts
  src/controllers/review.controller.ts
  src/repositories/review.repository.ts
  src/routes/review.router.ts
  src/services/review.service.ts
  src/types/review.type.ts
Labels: BE, Endpoint

#21 [김다은] 대기 중인 견적, 상세, 견적 확정하기 api까지 완료
  src/app.ts
  src/controllers/customerEstimate.controller.ts
  src/repositories/customerEstimate.repository.ts
  src/routes/customerEstimate.router.ts
  src/services/customerEstimate.service.ts
Labels: Feature, BE

#25 알림 관련 bug fix
  src/controllers/notification.controller.ts
Labels: BE, Fix

#26 [김다은] 받았던 견적 리스트 & 상세 조회 api
  src/controllers/customerEstimate.controller.ts
  src/repositories/customerEstimate.repository.ts
  src/routes/customerEstimate.router.ts
  src/services/customerEstimate.service.ts
Labels: Feature, BE

#29 [fix 이지수] 스키마 대폭 수정
  prisma/migrations/20250718092802_update_schema/migration.sql
  prisma/migrations/20250718094727_update_schema/migration.sql
  prisma/schema.prisma
Labels: Fix

#31 [Feat] 지정 견적 요청 로직 구현 및 관련 리팩토링
  src/controllers/estimateReq.controller.ts
  src/middlewares/passport/jwtStrategy.ts
  src/repositories/estimateReq.repository.ts
  src/routes/estimateReq.router.ts
  src/services/estimateReq.service.ts
Labels: Chore, Feature

#32 [FEAT] 찜하기, 리뷰 페이지네이션
  src/controllers/driver.controller.ts
  src/controllers/favorite.controller.ts
  src/repositories/driver.repository.ts
  src/repositories/favorite.repository.ts
  src/routes/driver.router.ts
  src/routes/favorite.router.ts
  src/services/driver.service.ts
  src/services/favorite.service.ts
  src/types/index.d.ts
Labels: Feature, BE, Endpoint

#33 feat: 활성 견적 조회 api 추가
  src/controllers/estimateReq.controller.ts
  src/middlewares/passport/jwtStrategy.ts
  src/routes/estimateReq.router.ts
  src/services/estimateReq.service.ts
Labels: Feature, Endpoint

#34 [FIX] find driver
  src/controllers/driver.controller.ts
  src/repositories/driver.repository.ts
  src/routes/driver.router.ts
Labels: Fix, Endpoint

#38 feat: notification BE
  package-lock.json
  package.json
  src/controllers/customerEstimate.controller.ts
  src/controllers/driver.controller.ts
  src/controllers/estimateReq.controller.ts
  src/controllers/notification.controller.ts
  src/repositories/address.repository.ts
  src/repositories/auth.repository.ts
  src/repositories/customerEstimate.repository.ts
  src/repositories/driver.repository.ts
  src/repositories/notification.Repository.ts
  src/routes/notification.router.ts
  src/services/auth.service.ts
  src/services/customerEstimate.service.ts
  src/services/notification.service.ts
  src/services/review.service.ts
  src/types/notification.type.ts
  src/utils/notificationMessage.ts
  src/utils/notificationMoveDaySchedule.ts
Labels: Feature, BE

#39 [Fix 이지수] 소셜로그인 구현 완료 및 충돌 수정
  src/controllers/auth.controller.ts
  src/middlewares/passport/socialStrategy.ts
  src/services/auth.service.ts
Labels: Feature, Fix

#41 [기능] 기사 견적 관련 API 4종 구현
  driver.http
  src/controllers/driver.controller.ts
  src/repositories/driver.repository.ts
  src/routes/driverPrivate.router.ts
  src/services/driver.service.ts
Labels: Feature, BE

#42 [chore] 불필요한 파일 정리
  auth.http
  dani.http
  driver.http
Labels: Chore, BE

#44 chor: 주석삭제
  src/controllers/driver.controller.ts
  src/controllers/notification.controller.ts
  src/repositories/notification.Repository.ts
  src/routes/notification.router.ts
  src/services/notification.service.ts
  src/types/notification.type.ts
  src/utils/moveReminder.ts
  src/utils/notificationMessage.ts
  src/utils/notificationMoveDaySchedule.ts
Labels: Refactor

#45 [bug fix] 실시간 알림
  src/services/notification.service.ts
Labels: BE, Fix

#46 fix: 알림 지역 텍스트명 수정
  src/services/notification.service.ts
  src/types/notification.type.ts
  src/utils/notificationMessage.ts
Labels: Chore, BE

#48 [FIX]: 찜한 기사님 api 수정
  src/controllers/driver.controller.ts
  src/repositories/driver.repository.ts
  src/repositories/favorite.repository.ts
  src/routes/driver.router.ts
  src/services/driver.service.ts
Labels: Fix

#50 fix: 충돌 해결 후 저장...
  src/controllers/driver.controller.ts
  src/repositories/driver.repository.ts
  src/services/driver.service.ts
Labels: Fix

#51 [김다은] 내견적관리 api 부분 수정
  src/controllers/customerEstimate.controller.ts
  src/repositories/customerEstimate.repository.ts
  src/services/customerEstimate.service.ts
Labels: BE, Fix

#53 [FIX] 활성 견적 요청 조회 로직 수정 및 기사 응답 수 제한 추가
  src/repositories/driver.repository.ts
  src/repositories/estimateReq.repository.ts
Labels: Feature, BE, Fix

#54 [FIX] 지정 견적 요청 여부 전달
  src/services/driver.service.ts
Labels: Feature, Fix

#55 [김다은] 내견적관리에 알림기능 합치기 + 찜하기 목록 api 수정
  src/controllers/customerEstimate.controller.ts
  src/controllers/favorite.controller.ts
  src/repositories/customerEstimate.repository.ts
  src/repositories/favorite.repository.ts
  src/services/customerEstimate.service.ts
  src/services/favorite.service.ts
  src/services/notification.service.ts
Labels: BE, Fix

#56 [Fix 이지수] auth 새로운 api 추가 및 프로필 유효성 검사 추가
  src/controllers/auth.controller.ts
  src/repositories/auth.repository.ts
  src/repositories/notification.repository.ts
  src/repositories/profile.repository.ts
  src/routes/auth.router.ts
  src/services/profile.service.ts
Labels: Fix

#57 [feat이지수]:프로필 이미지 업로더 및 API 추가
  package-lock.json
  package.json
  src/controllers/profile.controller.ts
  src/middlewares/uploadMiddleware.ts
  src/routes/profile.router.ts
  src/services/notification.service.ts
  src/types/multer-s3.d.ts
Labels: Feature

#59 Feat:리뷰 api 수정
  src/app.ts
  src/controllers/review.controller.ts
  src/repositories/review.repository.ts
  src/routes/review.router.ts
  src/services/notification.service.ts
  src/services/review.service.ts
Labels: Feature, Fix

#61 [기능] 반려요청 페이지 및 견적상세 페이지 API 연동
  prisma/schema.prisma
  src/repositories/driver.repository.ts
  src/services/notification.service.ts
Labels: BE, Fix

#62 Feat: 리뷰 POST, GET, DELETE 구현 및 수정
  src/controllers/review.controller.ts
  src/repositories/driver.repository.ts
  src/repositories/review.repository.ts
  src/routes/review.router.ts
  src/services/review.service.ts
  src/types/review.type.ts
Labels: Feature, BE, Endpoint

#63 Feat:리뷰 페이지네이션 적용위한 API 수정
  src/controllers/review.controller.ts
  src/repositories/review.repository.ts
  src/services/review.service.ts
Labels: Feature, Refactor, Endpoint

#64 [fix: 이지수] name 정보 출력하는 api에 프로필 정보 추가
  src/controllers/auth.controller.ts
  src/repositories/auth.repository.ts
Labels: Fix

#72 docs: 주소, 견적요청 Swagger 작성
  openapi.yaml
Labels: Chore

#73 알림 swagger 작성
  openapi.yaml
Labels: Chore

#74 [김다은] 내견적관리 api 테스트 코드 작성
  src/controllers/customerEstimate.controller.test.ts
  src/repositories/customerEstimate.repository.test.ts
  src/services/customerEstimate.service.test.ts
Labels: BE, Test

#76 [김다은] controller에서 알림 호출 에러 해결
  src/controllers/customerEstimate.controller.test.ts
Labels: Fix, Test

#77 feat: 견적 요청 날짜 유효성 수정
  package-lock.json
  package.json
  src/services/estimateReq.service.test.ts
  src/services/estimateReq.service.ts
Labels: Fix, Refactor, Test

#79 Test: review 테스트 코드 작성
  package-lock.json
  src/controllers/review.controller.test.ts
  src/repositories/review.repository.test.ts
  src/repositories/review.repository.ts
  src/services/review.service.test.ts
  src/services/review.service.ts
Labels: Refactor, Test

#80 [feat/fix] 견적 관련 기능 개선 및 에러 수정
  package-lock.json
  src/app.ts
  src/controllers/driver.controller.ts
  src/repositories/driver.repository.ts
  src/routes/admin.router.ts
  src/utils/estimateCompletionScheduler.ts
Labels: Feature, BE, Fix

#82 [Fix, test/authtest ] 테스트 코드 작성 및 로그인api에 유저타입 추가, 소셜로그인 토큰 로직 수정
  package-lock.json
  package.json
  src/controllers/auth.controller.test.ts
  src/controllers/auth.controller.ts
  src/controllers/profile.controller.test.ts
  src/controllers/profile.controller.ts
  src/repositories/auth.repository.test.ts
  src/repositories/profile.repository.test.ts
  src/repositories/profile.repository.ts
  src/routes/profile.router.ts
  src/services/auth.service.test.ts
  src/services/auth.service.ts
  src/services/profile.service.test.ts
  src/services/profile.service.ts
Labels: Fix, Test
