Repository sebiny/6-moving-team2-BE, pull requests merged in 2025-08, with the labels that each got.

#84 [TEST] driver test
  src/controllers/driver.controller.test.ts
  src/controllers/driver.controller.ts
  src/controllers/favorite.controller.test.ts
  src/controllers/favorite.controller.ts
  src/repositories/driver.repository.test.ts
  src/repositories/driver.repository.ts
  src/repositories/favorite.repository.test.ts
  src/repositories/favorite.repository.ts
  src/services/driver.service.test.ts
  src/services/driver.service.ts
  src/services/favorite.service.test.ts
  src/services/favorite.service.ts
Labels: Fix, Test

#86 [Fix/logintoken 이지수] 토큰 설정값 통일
  src/controllers/auth.controller.test.ts
  src/controllers/auth.controller.ts
  src/controllers/profile.controller.test.ts
  src/controllers/profile.controller.ts
  src/utils/getCookieDomain.ts
Labels: Fix

#88 [fix 이지수]이름 유효성 검사 제거 및 소셜로그인 토큰 도메인 재설정2
  src/services/auth.service.ts
  src/services/profile.service.ts
Labels: Fix

#89 fix:이름 유효성 검사 제거 및 소셜로그인 토큰 도메인 재설정복원
  src/utils/getCookieDomain.ts
Labels: Fix

#90 [김다은] 공유하기 api
  src/app.ts
  src/controllers/shareEstimate.controller.ts
  src/routes/shareEstimate.router.ts
Labels: Feature, Endpoint

#91 [fix 이지수 ]소셜로그인 토스트 모달 생성을 위한 쿠키 추가 및 helmet, morgan 추가
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.controller.ts
Labels: Fix

#92 Fix: review 기사 평균 별점 오류, test 오류
  package-lock.json
  src/controllers/review.controller.test.ts
  src/services/review.service.test.ts
  src/services/review.service.ts
Labels: Fix

#94 Fix/review driver
  package-lock.json
  src/services/review.service.ts
Labels: Fix

#96 [FIX] 리뷰 오류 수정
  src/repositories/driver.repository.ts
Labels: Fix

#97 [김다은] 견적서 공유하기 최종 수정
  src/controllers/shareEstimate.controller.ts
Labels: Fix

#98 [김다은] 견적확정 건수 증가
  src/controllers/customerEstimate.controller.ts
  src/repositories/customerEstimate.repository.ts
Labels: BE, Fix

#99 [Test] driver 모듈 테스트 코드 작성 및 Swagger 문서 추가
  openapi.yaml
  package-lock.json
  src/controllers/driver.controller.ts
  src/controllers/driverPrivate.controller.test.ts
  src/repositories/driver.repository.ts
  src/repositories/driverPrivate.repository.test.ts
  src/repositories/estimateReq.repository.test.ts
  src/services/driver.service.ts
  src/services/driverPrivate.service.test.ts
  src/services/estimateCompletion.service.test.ts
  src/services/estimateReq.service.test.ts
Labels: BE, Test

#104 [Fix] 테스트 수정까지 완료
  src/repositories/driverPrivate.repository.test.ts
Labels: BE, Test

#113 feat: 견적 요청 에러메세지 다국어 추가
  src/controllers/estimateReq.controller.ts
  src/services/estimateReq.service.ts
Labels: Feature

#114 fix: 환경변수 설정
  .github/workflows/deploy.yml
Labels: Chore

#115 fix: 견적요청 테스트 실패 코드 수정
  src/controllers/estimateReq.controller.test.ts
  src/services/estimateReq.service.test.ts
Labels: Fix

#117 [Chore 이지수] auth, profile 스웨거 작성
  openapi.yaml
Labels: Fix

#118 fix:deploy 폴더 수정
  .github/workflows/deploy.yml
Labels: Chore

#122 fix: 기사 견적 요청 조회 및 생성 시 응답 제한 로직 개선
  src/repositories/driver.repository.ts
  src/repositories/driverPrivate.repository.test.ts
Labels: BE, Fix

#123 [황수정] 소셜로그인 환영알림
  src/services/auth.service.ts
Labels: Feature

#125 [김다은] 내견적관리 api에서 driver.id 추가
  src/repositories/customerEstimate.repository.ts
Labels: BE, Fix

#126 [fix 이지수] 요청제한 미들웨어 코드 수정
  src/controllers/auth.controller.ts
  src/middlewares/authLimiter.ts
  src/routes/auth.router.ts
Labels: Fix

#128 [Refactor] cron스케줄러 모듈화 및 테스트환경 조건부처리
  src/app.ts
  src/utils/cronScheduler.test.ts
  src/utils/cronScheduler.ts
Labels: BE, Refactor

#129 Fix/review stars
  openapi.yaml
  src/repositories/driver.repository.ts
  src/routes/review.router.ts
  src/services/review.service.ts
Labels: Fix, Refactor

#131 [Feat/cloudfront 이지수] s3앞에 클라우드 프론트 추가
  package-lock.json
  package.json
  src/controllers/profile.controller.ts
  src/middlewares/uploadMiddleware.ts
  src/types/multer-s3.d.ts
Labels: Feature

#132 [fix:profile 이지수]테스트 타입 에러 해결
  src/controllers/profile.controller.test.ts
Labels: Fix

#134 [김다은] 내 견적관리 통합테스트 작성
  package-lock.json
  package.json
  src/integration-test/customerEstimate.test.ts
  src/routes/customerEstimate.router.ts
  src/utils/resetDB.ts
Labels: BE, Test

#133 Fix:review
  src/repositories/review.repository.ts
  src/services/review.service.ts
Labels: Fix

#137 [FEAT] test
  src/integration-test/customerEstimate.test.ts
  src/integration-test/driver.test.ts
  src/integration-test/review.test.ts
Labels: Test

#138 [황수정] notification supertest
  jest.config.js
  src/integration-test/notification.test.ts
  tsconfig.json
Labels: Test

#139 [Test/auth 이지수] auth 통합 테스트 코드 작성
  src/integration-test/auth.test.ts
  src/middlewares/authLimiter.ts
  src/routes/auth.router.ts
  src/utils/resetDB.ts
Labels: Test

#140 test: EstimateRequest 통합 테스트 작성
  src/integration-test/estimateReq.test.ts
Labels: Test

#141 Fix: review
  src/repositories/review.repository.test.ts
  src/repositories/review.repository.ts
Labels: Fix

#144 [Fix/authnametest 이지수] 이름유효성검사 추가 및 auth 테스트 계정 수정
  src/integration-test/auth.test.ts
  src/services/auth.service.ts
  src/services/profile.service.ts
Labels: Fix, Test

#143 feat(cache): Redis 적용 및 테스트 환경 분리
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/middlewares/cacheMiddleware.ts
  src/routes/auth.router.ts
  src/routes/customerEstimate.router.ts
  src/routes/driver.router.ts
  src/routes/driverPrivate.router.ts
  src/routes/estimateReq.router.ts
  src/routes/favorite.router.ts
  src/routes/notification.router.ts
  src/routes/review.router.ts
  src/routes/shareEstimate.router.ts
Labels: Chore, Feature, BE

#145 fix: estimateReq 통합테스트 fail 수정
  src/integration-test/estimateReq.test.ts
  src/middlewares/cacheMiddleware.ts
Labels: Fix

#147 [Test] 기사님 통합테스트작성
  src/integration-test/driverPrivate.test.ts
Labels: BE, Test

#149 [Fix/profilenickname 이지수] 기사 닉네임 중복 검사 로직 및 메세지 추가
  src/repositories/profile.repository.ts
  src/services/profile.service.ts
Labels: Fix

#151 [Fix/profilenickname 이지수] auth 테스트 코드 에러 수정
  src/integration-test/auth.test.ts
Labels: Test

#152 Feat/deep l
  src/middlewares/cacheMiddleware.ts
  src/routes/translateRouter.ts
Labels: Fix

#154 fix: redis 적용 메소드 확장
  src/middlewares/cacheMiddleware.ts
  src/routes/translateRouter.ts
Labels: Fix

#155 fix: cacheMiddleware 초기화
  src/middlewares/cacheMiddleware.ts
  src/routes/translateRouter.ts
Labels: Fix
